baseURL = "https://mikotorei.github.io/onceworld-miko/"
languageCode = "ja-jp"
title = "OnceWorld DB"

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[mediaTypes]
  [mediaTypes."application/javascript"]
    suffixes = ["js"]

[outputFormats]
  [outputFormats.MonsterData]
    mediaType = "application/javascript"
    baseName = "monsters-data"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "MonsterData"]
