baseURL = "https://mikotorei.github.io/onceworld-miko/"
languageCode = "ja-jp"
title = "OnceWorld DB"

disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
